### ISSUE TITLE
The user isn't able to name the current running

### ISSUE THREAD

**Issue by eszterjonas** [lavee1998/RunningManager#26]

**Comment by eszterjonas** [comment]
Somehow the users should be able to save a running with a name:

- When they click on Save, a pop up should appear
- When they Stop a Running, a pop up should appear
- On the Details screen an input field with a default value should be displayed

These are some possible solutions, that came to my mind. Any other, better ideas are welcomed :)
Also the redux should be updated to handle the names.

**Comment by b1v655** [comment]
User can choose name for his run.
