### ISSUE TITLE
Speed calculation fix

### ISSUE THREAD

**Issue by eszterjonas** [lavee1998/RunningManager#68]
The application should handle the big differences (due to the wrong gps coordinates).

**Comment by b1v655** [comment]
updateLocation function code refactored. Tested once, on walking.
![186510059_297310135328728_6748516675168814028_n](https://user-images.githubusercontent.com/79355535/118320009-e9f6f900-b4fb-11eb-8e80-3c5ed0fd1db8.jpg)
![185989412_984944488944522_8594504414687332776_n](https://user-images.githubusercontent.com/79355535/118320018-ed8a8000-b4fb-11eb-9947-408f28d69e2b.jpg)
